server:
  port: 8083
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notification-service-group
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages:
                ru.semstore.common.dto
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
            trust: ${MAIL_HOST}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never