services:
  discovery-server:
    container_name: discovery-server
    build:
      context: .
      dockerfile: backend/discovery-server/Dockerfile
    ports:
      - "8761:8761"

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: backend/gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_started
      user-service:
        condition: service_started
      order-service:
        condition: service_started
    env_file:
      - .env

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: backend/user-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      user-service-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  user-service-db:
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/user-service-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: backend/order-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      discovery-server:
        condition: service_started
      user-service:
        condition: service_started
      order-service-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_ORDER_SERVICE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  order-service-db:
    container_name: order-service-db
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres/order-service-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_ORDER_SERVICE_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10