services:
  user-service-db:
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres/user-service-db:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10