server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "${GATEWAY_ORIGIN}"
              - "${USER_SWAGGER_ORIGIN}"
              - "${ORDERS_SWAGGER_ORIGIN}"
              - "${FRONTEND_ORIGIN}"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**, /auth/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - AuthFilter
        - id: user-service-swagger-redirect
          uri: no://op
          predicates:
            - Path=/user-service/swagger
          filters:
            - RedirectTo=302,${USER_SWAGGER_ORIGIN}/swagger-ui/index.html
        - id: order-service-swagger-redirect
          uri: no://op
          predicates:
            - Path=/order-service/swagger
          filters:
            - RedirectTo=302,${ORDERS_SWAGGER_ORIGIN}/swagger-ui/index.html
      default-filters:
        - RemoveRequestHeader=X-User-Id

eureka:
  client:
    registryFetchIntervalSeconds: 3
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}