FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY backend/pom.xml .
COPY backend/order-service/pom.xml ./order-service/
COPY backend/discovery-server/pom.xml ./discovery-server/
COPY backend/gateway/pom.xml ./gateway/
COPY backend/user-service/pom.xml ./user-service/
COPY backend/common-dtos/pom.xml ./common-dtos/
COPY backend/notification-service/pom.xml ./notification-service/
COPY backend/notification-service/src ./notification-service/src/
COPY backend/common-dtos/src ./common-dtos/src/
RUN mvn package -pl notification-service -am -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/notification-service/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]