package ru.semstore.userservice.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    ADDRESS_COUNT_LIMIT,
    ADDRESS_OWNER_CONFLICT,
    ADDRESS_DELETED,
    USER_ALREADY_EXISTS,
    INVALID_PASSWORD,
    SAME_PASSWORD,
    FORBIDDEN,
    UNAUTHORIZED,
    INVALID_REFRESH_TOKEN,
    INVALID_TOKEN,
    INTERNAL_SERVER_ERROR,
    METHOD_ARGUMENT_NOT_VALID,
    MISSING_REQUEST_HEADER,
    METHOD_ARGUMENT_TYPE_MISMATCH,
    HTTP_MESSAGE_NOT_READABLE
}
